//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module API {
	export class Company
	{
		public Id: string;
		public Name: string;
		public Country: string;
		public City: string;
		public Contacts: string[];
		public Tags: string[];
	}
	export class RemoteWorking
	{
		public WorkType: number;
		public WorkRestrictions: string[];
	}
	export class Role
	{
		public Id: string;
		public Company: API.Company;
		public CompanyId: string;
		public Source: API.Source;
		public Title: string;
		public Test: string;
		public URL: string;
		public HasAdvertisedSalary: boolean;
		public AdvertisedSalaryFloor: number;
		public AdvertisedSalaryCeiling: number;
		public RemoteWorking: API.RemoteWorking;
		public State: number;
		public NumStages: number;
		public CurrentStage: number;
		public Stage: number;
		public Tags: string[];
		public Contacts: string[];
		public Notes: string;
	}
	export class Source
	{
		public Id: string;
		public Name: string;
		public URL: string;
	}
	export class Tag
	{
		public Id: string;
		public Name: string;
		public Category: string;
	}
}
